sudo: false
branches:
  only:
    - master
cache:
  directories:
    - node_modules
  language: node_js
os:
  - linux
  - osx
  # - windows
node_js:
  - 10
  - 12
  - 14
  - "stable"
before_install:
  - npm update
install: npm install
script:
  - npm test
  - npm run coveralls
email:
  on_failure: change
  on_success: never
after_success: npm run coverage
